# Generated by Django 5.2.5 on 2025-08-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='DATE_OF_BIRTH',
            new_name='date_of_birth',
        ),
    ]
